# Weight & balance input file for wb-katane.py
#
# Units:
# weight in kilogram (kg)
# arm in meters (m)
# fuel in liters (l)
#
title = "Diamond Katana"

callsign = "D-ECPU"
empty_weight = 529.55
empty_moment = 179.40

pilot_weight = 75.0
pax_weight = 65.0

baggage = 2.0
fuel = 75

